# Generated by Django 4.1.1 on 2022-09-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_type_employee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
    ]
