# Generated by Django 4.1.1 on 2022-09-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_alter_type_options_alter_employee_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
