# Generated by Django 4.1.1 on 2022-10-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_category_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=60, unique=True, verbose_name="Nombre"),
        ),
    ]
